# Generated by Django 3.0.8 on 2020-07-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name_plural': 'blog_posts'},
        ),
    ]
