# Generated by Django 3.0.8 on 2020-07-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200713_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
    ]
